# generate a docker-compose.yml configversion: '3.8'

services:
  library-mysql:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library
      MYSQL_USER: libuser
      MYSQL_PASSWORD: libpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql